### ISSUE TITLE
config.ini failed to open stream

### ISSUE THREAD

**Issue by PitifulCanine3** [rogierkn/PrettyBoot#11]
Hello,

I have tried to setup PrettyBoot on my website but i seem to be getting an error in the header of the site saying \/

Warning: parse_ini_file(./application/config/config.ini): failed to open stream: No such file or directory in /home/.../public_html/.../application/libraries/inihandle.php on line 54

This error causes the site to become unusable and i have followed all of the instructions in README.md.

![screenshot](https://cloud.githubusercontent.com/assets/10534452/8630895/01f8e508-2764-11e5-8318-64bfc6abbd54.png)

**Comment by rogierkn** [comment]
Try creating that .ini file at that path.
On Jul 11, 2015 01:27, Ross <notifications@github.com> wrote:Hello,

I have tried to setup PrettyBoot on my website but i seem to be getting an error in the header of the site saying \/

Warning: parse_ini_file(./application/config/config.ini): failed to open stream: No such file or directory in /home//public_html//application/libraries/inihandle.php on line 54

This error causes the site to become unusable and i have followed all of the instructions in README.md.

**Comment by PitifulCanine3** [comment]
A config.ini file is already in that folder

**Comment by PitifulCanine3** [comment]
The conifg.ini that was in that folder came with the base PrettyBoot installation and has settings in.

**Comment by rogierkn** [comment]
Make sure you set the right permissions, that the PHP script can actually reach and read that file.

**Comment by PitifulCanine3** [comment]
I've set the permissions on the PHP script and i'm still having an issue :/

**Comment by rogierkn** [comment]
That sucks...
Anyhow, I suggest you to use another source. PrettyBoot is pretty outdated.

**Comment by PitifulCanine3** [comment]
Alright, thanks for your support and good luck in your future projects :).
