### ISSUE TITLE
Links Broken

### ISSUE THREAD

**Issue by gh0stshell** [rogierkn/PrettyBoot#9]
Have it up and running, but when trying to register, domain.com/user/register I get a 404, how do I get the links setup correctly?

**Comment by rogierkn** [comment]
Set up mod rewrite properly for apache.

**Comment by gh0stshell** [comment]
Did that and fixed one other issue, now I get an error someone else got about no input file. I believe you said to install Laravel 3, but I can only find the setup for 4.

**Comment by gh0stshell** [comment]
stressme.net/user/register

No input file specified.

**Comment by gh0stshell** [comment]
Any help on this error when registering?

No input file specified

**Comment by rogierkn** [comment]
There are lots of people with the same problem online, find your solution there as there may be multiple causes.

**Comment by gh0stshell** [comment]
This is not going to be closed until this is working

**Comment by gh0stshell** [comment]
where online

https://www.google.com/search?q=pretty+boot+file+not+specified&oq=pretty+boot+file+not+specified&aqs=chrome..69i57.6315j0j7&sourceid=chrome&es_sm=93&ie=UTF-8

**Comment by gh0stshell** [comment]
you are missing steps in the Install section

**Comment by gh0stshell** [comment]
add the missing steps and all is working now

**Comment by gh0stshell** [comment]
I do not mark this supported

**Comment by rogierkn** [comment]
You done? Cool
